### ISSUE TITLE
 `inline-block` for `<mfrac>`

### ISSUE THREAD

**Issue by Yaffle** [fred-wang/mathml.css#2]
Hello,
Did you consider of using `inline-block` for `<mfrac>`?

after/before
![vertical-align](https://cloud.githubusercontent.com/assets/130792/7592054/bdc2ad76-f8ea-11e4-82b3-13fa284291fc.png)

```
mfrac {
  display: inline-block !important;
  vertical-align: -50%;
}
mfrac > *:first-child {
  display: block !important;
}
mfrac > * + * {
  display: inline-block !important;
  vertical-align: top;
}
```

**Comment by fred-wang** [comment]
Thanks, I think I tried several things and I end up with the current one, which I knew didn't work very well for nested equations. Have you tried your proposal for various complex cases?

Can you please submit a pull request?

**Comment by fred-wang** [comment]
Thanks, I merged it.

**Comment by Yaffle** [comment]
My mistake:
this solution does not work in "Quirks Mode" (you should always have <!DOCTYPE html>). And it doesn't work well in IE 9 - 11, Konqueror and Safari 5.1.
