### ISSUE TITLE
Square root on fractions

### ISSUE THREAD

**Issue by codeuser10** [fred-wang/mathml.css#6]
I have equations that require square roots over fractions. The current css places the root only over numerator. 
Here's how  it looks on firefox, 
![firefox](https://cloud.githubusercontent.com/assets/16138439/21995558/b08e26c4-dc4d-11e6-942d-3eab8f54943d.PNG)

and this is the same equation on chrome
![chrome](https://cloud.githubusercontent.com/assets/16138439/21995578/c67c1928-dc4d-11e6-8fcf-eb92fe382115.PNG)

I tried increasing the font-size for radic but it doesn't work for all cases.

**Comment by fred-wang** [comment]
This is by design and more general operator stretching will not be implemented with this stylesheet. Please star https://bugs.chromium.org/p/chromium/issues/detail?id=6606 to vote for Chrome's native mathematical rendering.

**Comment by Yaffle** [comment]
It may look better if to place the radical in the middle...
