### ISSUE TITLE
more?

### ISSUE THREAD

**Issue by bkardell** [fred-wang/mathml.css#7]
I came across this specific repo while looking through some other things and, looking at it, I am wondering if there are improvements that could be made with advancements in CSS.  `mmultiscripts` for example is currently pretty bad, but it seems like you could improve support pretty significantly on that one by using grid or inline grid here to divide up the matrix and place the boxes?  Perhaps that is naieve based on my limited understanding of the matrix stuff?

**Comment by fred-wang** [comment]
I mean, probably we can do more and I'm happy to accept PR from other people. But do we really need to spend time on that instead of native MathML support? Can we close this?

**Comment by fred-wang** [comment]
Closing this as I'm not personally interested. Instead I'll open a new issue if someones is interested in contributing more.
